/*!
 * Arithmetic — module manifest.
 */
(function () {
  MR.Content.registerModule({
    id: "arithmetic",
    title: "Arithmetic",
    subtitle: "Numbers & operations",
    emoji: "🧮",
    accent: "#f4c77a",
    grade: "Gr. 3–4",
    order: 1,
    status: "live",
    chapters: [
      "ch-ari-01-forest",
      "ch-ari-02-brook",
      "ch-ari-03-berries",
      "ch-ari-04-mouse-market",
      "ch-ari-05-library",
      "ch-ari-06-bakery",
      "ch-ari-07-night-sky",
      "ch-ari-08-hedgehog-heist",
      "ch-ari-09-fireflies",
      "ch-ari-10-puppy-picnic",
      "ch-ari-11-kitten-quilt",
      "ch-ari-12-fox-fair",
      "ch-ari-13-deer-dale",
      "ch-ari-14-honey-hunt",
      "ch-ari-15-thousand-stars",
      "ch-ari-16-grand-revue",
    ],
    arcadeGames: [
      "arc-bubble-blocks",
      "arc-treasure-trail",
      "arc-multiply-mountain",
      "arc-share-shack",
      "arc-pie-pals",
      "arc-place-parade",
      "arc-word-wander",
      "arc-story-solver",
      "arc-pattern-parade",
      "arc-round-up",
      "arc-thousand-quest",
      "arc-ten-times",
      "arc-array-split",
      "arc-fraction-match",
    ],
    teachingOps: [
      "ari-op-addition",
      "ari-op-subtraction",
      "ari-op-add-sub-inverse",
      "ari-op-multiplication",
      "ari-op-division",
      "ari-op-mul-div-inverse",
      "ari-op-place-value",
      "ari-op-fractions",
      "ari-op-compare-fractions",
      "ari-op-fractions-numberline",
      "ari-op-word-problems",
      "ari-op-patterns",
      "ari-op-rounding",
      "ari-op-times-ten",
      "ari-op-distributive",
      "ari-op-equivalent-fractions",
    ],
    critterPool: [
      "baby-raccoon", "baby-otter", "baby-squirrel", "baby-mouse",
      "baby-koala", "baby-bunny", "baby-owl", "baby-hedgehog",
      "baby-skunk", "baby-puppy", "baby-kitten", "baby-fox",
      "baby-fawn", "baby-bear-cub", "baby-duckling", "baby-panda",
    ],
  });
})();
